name: build

on: 
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: gradle :release
      - name: upload jar file
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          tag: ${{ github.ref }}
          file: ./release/*.jar
          overwrite: true
          file_glob: true
